version: 2
jobs:
  build:
    working_directory: ~/AvaloniaBehaviors
    docker:
      - image: microsoft/dotnet:2.1.401-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Install
          command: |
            dotnet --info
            dotnet tool install -g Cake.Tool --version 0.30.0
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake build.cake --target="CircleCI" --platform="Any CPU" --configuration="Release"
    notify:
      webhooks:
        - url: https://webhooks.gitter.im/e/8b396be7e49e711c841c
