version: 2
jobs:
  build:
    working_directory: ~/AvaloniaBehaviors
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore samples/BehaviorsTestApplication.NetCore
      - run: dotnet build samples/BehaviorsTestApplication.NetCore/BehaviorsTestApplication.NetCore.csproj
